#!/bin/sh

# ARCHIVE EXTRACTION
# usage: ex <file>
function ex {
 if [ -z "$1" ]; then
    # display usage if no parameters given
    echo "Usage: ex <path/file_name>.<zip|rar|bz2|gz|tar|tbz2|tgz|Z|7z|xz|ex|tar.bz2|tar.gz|tar.xz>"
    echo "       extract <path/file_name_1.ext> [path/file_name_2.ext] [path/file_name_3.ext]"
 else
    for n in "$@"
    do
      if [ -f "$n" ] ; then
          case "${n%,}" in
            *.cbt|*.tar.bz2|*.tar.gz|*.tar.xz|*.tbz2|*.tgz|*.txz|*.tar)
                         tar xvf "$n"       ;;
            *.lzma)      unlzma ./"$n"      ;;
            *.bz2)       bunzip2 ./"$n"     ;;
            *.cbr|*.rar)       unrar x -ad ./"$n" ;;
            *.gz)        gunzip ./"$n"      ;;
            *.cbz|*.epub|*.zip)       unzip ./"$n"       ;;
            *.z)         uncompress ./"$n"  ;;
            *.7z|*.arj|*.cab|*.cb7|*.chm|*.deb|*.dmg|*.iso|*.lzh|*.msi|*.pkg|*.rpm|*.udf|*.wim|*.xar)
                         7z x ./"$n"        ;;
            *.xz)        unxz ./"$n"        ;;
            *.exe)       cabextract ./"$n"  ;;
            *.cpio)      cpio -id < ./"$n"  ;;
            *.cba|*.ace)      unace x ./"$n"      ;;
            *)
                         echo "ex: '$n' - unknown archive method"
                         return 1
                         ;;
          esac
      else
          echo "'$n' - file does not exist"
          return 1
      fi
    done
fi
}

IFS=$SAVEIFS

### ALIASES

# navigation
alias \
	..='cd ..' \
	...='cd ../..' \
	.3='cd ../../..' \
	.4='cd ../../../..' \
	.5='cd ../../../../..'

# eza
alias ls='eza --icons --color=always --group-directories-first'

# arch btw
alias p='sudo pacman'
alias orphan='sudo pacman -Rns $(pacman -Qtdq)'

# flags
alias \
	df='df -h' \
	free='free -m' \
	grep='grep --color=auto'

# system
alias \
	sdn='sudo shutdown -h now' \
	ka='killall' \
	jctl="journalctl -p 3 -xb"

# programs
alias \
	g="git" \
	r="ranger" \
	cat="bat" \
	yay="paru" \
	vim="nvim" \
	v="emacs -nw" \
	e="emacs -nw" \
	mp3="yt-dlp --extract-audio --audio-format mp3" \
	youtube-dl="yt-dlp" \
	neofetch="fastfetch --logo-type kitty --logo ".config/profile.jpg" --logo-height "15""
